title: "quarto-site-template ğŸ—ï¸"
date: last-modified
# date: today
author-title: ""
affiliation-title: ""
published-title: ""
modified-title: ""
title-block-categories: false
number-sections: false
bibliography: references.bib
# appendix-cite-as: display
favicon: "favicon.svg"
# twitter-card: true
site-url: "https://saforem2.github.io/quarto-site-template"
google-scholar: true
citeproc: true
# filters:
#   - lightbox
# lightbox: auto
project:
  render:
    - index.qmd
    # - qmd/**/*.qmd
    # - qmd/blog/*.qmd
  type: website
  output-dir: "docs"
  preview:
    port: 4609
author:
  name: "Sam Foreman [[{{< ai orcid >}}]{.orcid-green}](https://orcid.org/0000-0002-9981-0876)"
  url: https://samforeman.me
  email: foremans@anl.gov
citation:
   author: Sam Foreman
   type: webpage
   title: "quarto-site-template ğŸ—ï¸"
   url: https://saforem2.github.io/quarto-site-template
execute:
  # keep-ipynb: true
  # keep-md: true
  freeze: auto

metadata-files:
  - ./quarto/_website.yml
  - ./quarto/_format.yml
  # - _reveal.yml
